# NUMPY

#### NumPy is a fundamental package for scientific computing in python. It is a python library that provides a multi dimentional array objects and various derived objects such as masked arrays, matrices and an assortment of routines for fast operations on arrays including mathematical, logical, shape manipulation, sorting, selecting, i/o, discrete fourier transform, basic linear algebra, statistical operations, random simulations etc.

#### At the core of the NumPy package is the n-dimentional array objects. 

## Why NumPy ?

### 2008-2009, Data science was boom --> Matlab, R language (were popular not python)

## Data types in python --> list, dictionaries --> slow
Syntax --> Python --> Easy
## We needed speed and less memory to work with the huge amount of data.

NumPy --> C language --> wrapped --> python language
## NumPy --> syntax --> easy for beginners --> performing scientific calculations --> creating multi dimentional arrays --> speed is faster for applying operations --> less memory

### Libraries like scikit learn, tensorflow and pytorch requires input data in NumPy arrays or tensors.

## NumPy arrays vs python sequences

#### NumPy arrays have a fixed size at creation, unlike python lists which grow dynamically. Changing the size of an n-dimentional array will create a new array and delete the original.

#### The elements in a NumPy array are required to be of the same data type and thus will be of the same size in memory.

#### NumPy arrays facilitates advanced mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code than is possible using python's built in sequences. 

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install --upgrade pip

  Using cached pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.2.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [3]:
numpy_array = np.array([1,2,3,4,5]) #1-D array considered as vector


In [4]:
numpy_array

array([1, 2, 3, 4, 5])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
twodarray = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [7]:
twodarray = np.array([[1,2,3],[4,5,6]]) #considered as matrix

In [8]:
twodarray

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(twodarray)

numpy.ndarray

In [24]:
twodarray = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [10]:
twodarray

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
twodarray = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])

In [12]:
twodarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
twodarray = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [14]:
twodarray = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])

In [15]:
twodarray 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
threedarray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #considered as tensor

In [17]:
threedarray

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## np.array() ---> creating the multidimentional arrays

#### dtype parameter ---> which can help us out with deciding about the size of the elements/ data we are going to store inside our array

In [18]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [19]:
np.array([7,8,9,10,11],dtype=np.int64)

array([ 7,  8,  9, 10, 11])

In [20]:
np.array([7,8,9,10,11],dtype=np.float32)

array([ 7.,  8.,  9., 10., 11.], dtype=float32)

In [21]:
np.array([7,8,9,10,11],dtype=np.float64)

array([ 7.,  8.,  9., 10., 11.])

In [22]:
np.array([11,15,16,17],dtype=float)

array([11., 15., 16., 17.])

In [23]:
np.array([11,15,16,17],dtype=int)

array([11, 15, 16, 17])

In [24]:
np.array([11,15,16,17],dtype=bool)

array([ True,  True,  True,  True])

In [25]:
np.array([11,15,16,a],dtype=float)

NameError: name 'a' is not defined

In [26]:
np.array([11,15,16,17],dtype=bool)

array([ True,  True,  True,  True])

In [27]:
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [28]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## arangle() ---> It helps us out with providing the values over a certain range

In [29]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [30]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
arangle_data = np.arange(1,17)

In [32]:
arangle_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### reshape() ---> It helps us out with changing the shape of the array as per our needs

In [39]:
arangle_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [40]:
arangle_data.reshape(2,10)

ValueError: cannot reshape array of size 16 into shape (2,10)

In [41]:
arangle_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [44]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [ ]:
## ones() --> it can initialize the weight of the neurons in the neural network architecture

In [45]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## random() - It helps us out with generating any random values from 0 to 1 inside our matrix

In [51]:
np.random.random((3,4))

array([[0.88396953, 0.23660152, 0.79107925, 0.41730234],
       [0.09642573, 0.89790154, 0.52980135, 0.36578538],
       [0.20668643, 0.20953357, 0.2801018 , 0.30142994]])

## identity() - It help us out with creating the matrix as an identity matrix (square matrix)

In [55]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## linspace() ---> It make sure that every value within the given range is going to have similar distance from each other

In [56]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes 

## ndim --> It stands for n dimensions

In [57]:
arr = np.array([1,2,3])

In [58]:
arr

array([1, 2, 3])

In [59]:
arr.ndim

1

In [63]:
array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [64]:
array.ndim

3

In [65]:
ayy2 = np.array([[1,2],[3,4]]).ndim

In [66]:
ayy2

2

## shape --> It provides us with the idea about the rows, columns in our datasets or in array

In [2]:
ARray = np.array([[1,3,5],[4,5,6],[11,15,13]])

In [4]:
ARray

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [11, 15, 13]])

In [3]:
ARray.shape

(3, 3)

In [5]:
threedarray = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [6]:
threedarray

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [7]:
threedarray.shape

(2, 2, 2)

## size --> It provides us with the idea of total number of elements present inside our dataset or in array

In [8]:
array_element = np.arange(5,57)

In [9]:
array_element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56])

In [10]:
array_element.size

52

In [12]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [13]:
np.array([[1,2],[3,4],[5,6]], dtype=np.int32).itemsize

4

## itemsize --> It provides with the idea about the size of a unique element inside our array in bytes

## dtype --> It provides us with the idea about the type of every item inside our array.

In [14]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

## astype() --> It will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numPy as well for getting the data type changed of our overall array.

In [15]:
array = np.arange(1,10).reshape(3,3)

In [16]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
type(array)

numpy.ndarray

In [19]:
array.dtype

dtype('int64')

In [20]:
array=array.astype('float64')

In [21]:
array.dtype

dtype('float64')

## Mathematical Operations in NumPy

## Scalar Operations --> A scalar value operation will be done with the array or a numeric value (e.g. 1,2,4)

In [22]:
array = np.random.random((3,3))*100

In [25]:
array = np.round(array)

In [27]:
array = array.astype('int32')

In [28]:
array

array([[ 4, 71, 24],
       [40, 41, 89],
       [18, 25, 26]], dtype=int32)

#### Scalar operations with our matrix or array

In [29]:
array + 2

array([[ 6, 73, 26],
       [42, 43, 91],
       [20, 27, 28]], dtype=int32)

In [31]:
array

array([[ 4, 71, 24],
       [40, 41, 89],
       [18, 25, 26]], dtype=int32)

In [30]:
array - 5

array([[-1, 66, 19],
       [35, 36, 84],
       [13, 20, 21]], dtype=int32)

In [32]:
array

array([[ 4, 71, 24],
       [40, 41, 89],
       [18, 25, 26]], dtype=int32)

In [33]:
array * 2

array([[  8, 142,  48],
       [ 80,  82, 178],
       [ 36,  50,  52]], dtype=int32)

In [34]:
array

array([[ 4, 71, 24],
       [40, 41, 89],
       [18, 25, 26]], dtype=int32)

In [35]:
array / 2

array([[ 2. , 35.5, 12. ],
       [20. , 20.5, 44.5],
       [ 9. , 12.5, 13. ]])

#### We can apply scalar operations with the array in terms of arithmetic operations

In [36]:
array

array([[ 4, 71, 24],
       [40, 41, 89],
       [18, 25, 26]], dtype=int32)

In [37]:
array > 60

array([[False,  True, False],
       [False, False,  True],
       [False, False, False]])

## Vector operations --> Operations will be in between the given number of matrices

In [39]:
arr_1 = np.arange(1,17).reshape(4,4)

In [40]:
arr_2 = np.arange(17,33).reshape(4,4)

In [41]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [43]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [44]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [46]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important functions in NumPy for machine learning and data science

## max() --> It is going to be used to calculate the max value inside a matrix or an array
## Syntax for max() --> np.max(array)

In [47]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
max = np.max(arr_1)

In [50]:
max

np.int64(16)

In [51]:
array_data = np.round(np.random.random((4,4))*100).astype('int32')

In [53]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

## axis --> It provides us with the idea about the any operational value inside a specific row or column or we can get a specific value row wise or column wise

#### axis = 0 --> column wise operation
#### axis = 1 --> row wise operation

In [54]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [55]:
np.max(array_data, axis=0)

array([82, 94, 54, 98], dtype=int32)

In [57]:
np.max(array_data, axis=1)

array([94, 74, 82, 98], dtype=int32)

## min() --> It will be used for calculating the minimum value from the matrix or array
## Syntax --> np.min()

In [58]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [59]:
np.min(array_data)

np.int32(6)

In [60]:
np.min(array_data, axis=1)

array([13,  6, 54, 34], dtype=int32)

In [61]:
np.min(array_data, axis=0)

array([15, 36,  6, 60], dtype=int32)

In [62]:
array = np.arange(1,10)

In [63]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.max(array)

np.int64(9)

In [65]:
np.min(array)

np.int64(1)

## sum() --> calculates the sum of all of the values of a given matrix 
## Syntax --> np.sum(array)

In [66]:
np.sum(array_data)

np.int64(834)

In [67]:
np.sum(array_data, axis=1)

array([188, 169, 262, 215])

In [68]:
np.sum(array_data, axis=0)

array([173, 265, 107, 289])

## prod() --> It helps with calculating the product of all values inside the matrix
## Syntax --> np.prod(array)

In [70]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [69]:
np.prod(array_data)

np.int64(-9029441378730733568)

In [71]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.prod(array)

np.int64(362880)

In [73]:
np.prod(array_data, axis=1)

array([ 1209780,   772560, 17557020,  5637744])

In [74]:
np.prod(array_data, axis=0)

array([ 1676490, 15275376,   143208, 25225200])

## Statistical functions in NumPy

## mean() --> syntax --> np.mean() --> it provides mean of all values inside the array or matrix

In [75]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [76]:
np.mean(array_data)

np.float64(52.125)

In [77]:
np.mean(array_data, axis=1)

array([47.  , 42.25, 65.5 , 53.75])

In [78]:
np.mean(array_data, axis=0)

array([43.25, 66.25, 26.75, 72.25])

## std() --> stands for standard deviation --> it provides with the standard deviation of all values of the matrix or array

In [79]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [80]:
np.std(array_data)

np.float64(27.292111955654878)

## axis=0 --> column wise std
## axis=1 --> row wise std

## median() --> to calculate median of all values in the array or matrix
## synax --> np.median()

In [81]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [82]:
np.median(array_data)

np.float64(57.0)

In [83]:
np.median(array_data, axis=0)

array([38. , 67.5, 23.5, 65.5])

In [84]:
np.median(array_data, axis=1)

array([40.5, 44.5, 63. , 41.5])

## var() --> it helps with calculating the variance of all values inside the array or matrix
## Syntax --> np.var()

In [85]:
array_data

array([[15, 94, 13, 66],
       [29, 74,  6, 60],
       [82, 61, 54, 65],
       [47, 36, 34, 98]], dtype=int32)

In [86]:
np.var(array_data)

np.float64(744.859375)

## Trigonometric functions

## sin() --> it provides sin value for the value we are going to pass inside it
## Syntax --> np.sin()

In [87]:
np.sin(0)

np.float64(0.0)

In [88]:
np.sin(60)

np.float64(-0.3048106211022167)

In [89]:
np.tan(45)

np.float64(1.6197751905438615)

In [90]:
np.cos(45)

np.float64(0.5253219888177297)

In [91]:
np.cos(12)

np.float64(0.8438539587324921)

## Dot product of matrices

## Syntax --> np.dot(matrix1, matrix2)

In [96]:
matrix_1 = np.round(np.random.random((3,4))*100).astype('int32')
matrix_2 = np.round(np.random.random((4,3))*100).astype('int32')


In [97]:
matrix_1

array([[99, 18, 91, 45],
       [47,  1, 11, 70],
       [78, 93, 92, 48]], dtype=int32)

In [98]:
matrix_2

array([[57, 13, 98],
       [28, 23,  6],
       [14, 32, 64],
       [52, 13, 80]], dtype=int32)

In [99]:
np.dot(matrix_1, matrix_2)

array([[ 9761,  5198, 19234],
       [ 6501,  1896, 10916],
       [10834,  6721, 17930]], dtype=int32)

## log() --> to calculate the log of all values of our matrix
## Syntax --> np.log()

In [100]:
matrix_1

array([[99, 18, 91, 45],
       [47,  1, 11, 70],
       [78, 93, 92, 48]], dtype=int32)

In [101]:
np.log(matrix_1)

array([[4.59511985, 2.89037176, 4.51085951, 3.80666249],
       [3.8501476 , 0.        , 2.39789527, 4.24849524],
       [4.35670883, 4.53259949, 4.52178858, 3.87120101]])

## exp() --> to calculate the exponential of all values inside the matrix
## Syntax --> np.exp()

In [102]:
matrix_1

array([[99, 18, 91, 45],
       [47,  1, 11, 70],
       [78, 93, 92, 48]], dtype=int32)

In [103]:
np.exp(matrix_1)

array([[9.88903032e+42, 6.56599691e+07, 3.31740010e+39, 3.49342711e+19],
       [2.58131289e+20, 2.71828183e+00, 5.98741417e+04, 2.51543867e+30],
       [7.49841700e+33, 2.45124554e+40, 9.01762841e+39, 7.01673591e+20]])

## round() --> it helps us with rounding off the float values to its nearest possible integer value
## Syntax --> np.round()
#### round off value for 1.7 --> 2
#### round off value for 1.3 --> 1

In [104]:
array = np.random.random((3,4))

In [109]:
array = array*10

In [110]:
np.round(array)

array([[ 5., 10.,  3.,  3.],
       [ 3.,  5.,  7.,  1.],
       [ 7.,  0.,  6.,  4.]])

In [ ]:
## round() --> 1.6-->2, 1.3-->1
## ceil() --> 1.6--2, 1.3-->2
## floor() --> 1.6-->1, 1.3-->1

## ceil() --> it provides us with the next correspondence value
## Syntax --> np.ceil()

In [112]:
array

array([[4.71270385, 9.89592746, 3.24488144, 2.64843282],
       [2.64194871, 4.7607758 , 7.17470024, 0.82672119],
       [7.1977875 , 0.10215493, 5.88868995, 4.02719078]])

In [113]:
np.ceil(array)

array([[ 5., 10.,  4.,  3.],
       [ 3.,  5.,  8.,  1.],
       [ 8.,  1.,  6.,  5.]])

## floor() --> It can provide us with the previous value
## Syntax --> np.floor()

In [114]:
array

array([[4.71270385, 9.89592746, 3.24488144, 2.64843282],
       [2.64194871, 4.7607758 , 7.17470024, 0.82672119],
       [7.1977875 , 0.10215493, 5.88868995, 4.02719078]])

In [115]:
np.floor(array)

array([[4., 9., 3., 2.],
       [2., 4., 7., 0.],
       [7., 0., 5., 4.]])

## transpose() --> It calculates the transpose of the given matrix
## Syntax --> np.transpose(array) or arr.T
## Transpose --> (i,j) --> (j,i)
#### e.g. (3,4) --> (4,3) 

In [119]:
array = np.arange(1,13).reshape(3,4)

In [120]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [122]:
np.transpose(array)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## ravel() --> It helps us out to convert n-d array in 1-d array 
## Syntax --> np.ravel()

In [123]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
array.ndim

2

In [125]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing and Slicing in NumPy


#### Indexing --> list[,size-1] --> to have the access over the values

In [126]:
array = np.round(np.random.random((5,5))*100).astype('int32')

In [127]:
array

array([[ 15,  54,  55,  17,  74],
       [ 20,  19,  17,  31,  23],
       [  0,  95,  42,  50,  74],
       [ 95, 100,   1,  32,  68],
       [ 82,  79,  21,  47,  28]], dtype=int32)

In [128]:
array_one = np.arange(1,10)

In [129]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
array_one[6]

np.int64(7)

In [131]:
array_one[-1]

np.int64(9)

In [133]:
array


array([[ 15,  54,  55,  17,  74],
       [ 20,  19,  17,  31,  23],
       [  0,  95,  42,  50,  74],
       [ 95, 100,   1,  32,  68],
       [ 82,  79,  21,  47,  28]], dtype=int32)

In [134]:
array[4,4]

np.int32(28)

In [136]:
## Indexing in 2-d array --> [row, column]
## Indexing in 3-d array --> [z-axis, row, column]

In [137]:
array[2,3]

np.int32(50)

In [138]:
array_three = np.arange(1,9).reshape(2,2,2)

In [139]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [140]:
array_three[1,0,1]

np.int64(6)

In [141]:
array

array([[ 15,  54,  55,  17,  74],
       [ 20,  19,  17,  31,  23],
       [  0,  95,  42,  50,  74],
       [ 95, 100,   1,  32,  68],
       [ 82,  79,  21,  47,  28]], dtype=int32)

## Slicing --> similar approach just like the list [:]
## 2-d array --> [row_1:row_2, col_1:col2]

In [142]:
array[:,2]

array([55, 17, 42,  1, 21], dtype=int32)

In [144]:
array[0,:]

array([15, 54, 55, 17, 74], dtype=int32)

In [145]:
array[2:4]

array([[  0,  95,  42,  50,  74],
       [ 95, 100,   1,  32,  68]], dtype=int32)

In [146]:
array[2:4,3:5]

array([[50, 74],
       [32, 68]], dtype=int32)

In [147]:
array[2:,1:4]

array([[ 95,  42,  50],
       [100,   1,  32],
       [ 79,  21,  47]], dtype=int32)

## Iterating over an array

In [148]:
array = np.arange(1,10)

In [149]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [151]:
array = np.arange(1,17).reshape(4,4)

In [152]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [154]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [155]:
array = np.arange(1,28).reshape(3,3,3)

In [156]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [157]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


## nditer() --> n-dimension iteration function --> it can help us out with iterating over every value in nd array

In [158]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [160]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [161]:
## 1-d array --> value by value
## 2-d array --> row by row on iteration
## 3-d array --> 2d array by 2d array



## Stacking and Splitting in arrays --> size of the array must be the same

## Stacking --> joining the array together
## Horizontal stacking --> row by row joining is done --> hstack()
## Vertical stacking --> column by column joining is done --> vstack()




In [162]:
array_one = np.arange(1,13).reshape(3,4)

In [163]:
array_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
array_two = np.arange(13,25).reshape(3,4)

In [165]:
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [166]:
horizontal_array = np.hstack((array_one, array_two))

In [168]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [169]:
horizontal_array = np.hstack((array_one, array_two, array_one, array_two))

In [170]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12, 21, 22, 23, 24]])

In [171]:
vertical_array = np.vstack((array_one, array_two))

In [172]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

## Horizontal split --> np.hsplit(array, number of parts you want your array to be splitted at)
## Vertical splits --> np.vsplit(array, number of parts you want your array to be splitted at)

In [173]:
np.hsplit(vertical_array, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [175]:
np.vsplit(vertical_array, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [176]:
np.vsplit(vertical_array, 3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]